### ISSUE TITLE
Can't find tests

### ISSUE THREAD

**Issue by ventsislav-georgiev** [cspotcode/vscode-mocha-latte#11]
My setup is running mocha through an npm script:
`node_modules/.bin/mocha --opts ./tests/mocha.opts`

and in the opts file I have all the options:
```
./tests/common
./tests/unit/*/*.js
./tests/unit/*/!(ui)/*.js
./tests/unit/*/!(ui)/**/*.js
--ui bdd
--recursive
--colors
--reporter mocha-jenkins-reporter
--reporter-options junit_report_path=reports/tests/unit.xml
```

I have setup the following `vscode-mocha-latte` options:
```
    "mocha.options": {
        "opts": "./tests/mocha.opts"
    }
```

Unfortunately, it does not seem to pick up the opts file, because when I execute the `Run All Tests` command its displays the warning `No tests found.`

**Comment by cspotcode** [comment]
I think that `--opts` might not be supported.  `"mocha.options"` is [passed as an options object to Mocha's JS API](https://github.com/cspotcode/vscode-mocha-latte/blob/master/worker/findtests.js#L43), not the command-line interface.  Mocha's [JS API documentation](https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically#set-options) does not mention `--opts`.

I agree with you that this ideally *should* be supported.  It's annoying to duplicate your options in two places.  However, at least for the time being, you'll have to do something like this in your VSCode settings:

```
"mocha.files.glob": [
  "./tests/common",
  "./tests/unit/*/*.js",
  "./tests/unit/*/!(ui)/*.js",
  "./tests/unit/*/!(ui)/**/*.js"
],
"mocha.options": {
  "ui": "bdd",
  "useColors": true
}
```

Please feel free to create a new issue requesting `--opts` support.  Or change this issue, whichever's easier.

**Comment by cspotcode** [comment]
I've created an issue to track `--opts`support, so I'm closing this one.
