### ISSUE TITLE
Cant found mocha commands

### ISSUE THREAD

**Issue by betososa** [cspotcode/vscode-mocha-latte#3]
Hi! I tried to run your extension in Ubuntu, but i always get this error

`command 'mocha.runAllTests' not found`

I dont know if i am missing a conf or something

**Comment by cspotcode** [comment]
What version of Ubuntu and VSCode are you running?

Also please click "Help -> Toggle Developer Tools", open the "Console" tab,
and include a screenshot or copy-paste of any messages.

**Comment by betososa** [comment]
Ubuntu 14.04.4 LTS
Visual Studio Code Version 1.7.1

![image](https://cloud.githubusercontent.com/assets/1018478/20017523/a5a9d1fc-a289-11e6-9703-7dc730e58774.png)

Thanks!

**Comment by cspotcode** [comment]
It looks like you have the old "Mocha" extension installed.  You'll have to
uninstall it; "Mocha Latte" is a replacement, at least until the original
author is able and willing to update the original.

Let me know if uninstalling "Mocha" fixes the problem.

**Comment by betososa** [comment]
i tried both
Here is with mocha latte
![image](https://cloud.githubusercontent.com/assets/1018478/20018132/149f847e-a28c-11e6-8b3d-f580256e24b2.png)

Thanks!

**Comment by bobderrico80** [comment]
I am having the same issue as well... Mocha Latte installed, the original Mocha plugin uninstalled. Ubuntu 16.04. Visual Studio Code 1.7.2. Node 6.5.0.

Here are the errors that are logged when I try to run any of the Mocha commands:
```
[Extension Host] Activating extension `cspotcode.vscode-mocha-latte` failed: tty.getWindowSize is not a function.
[Extension Host] Activating extension `cspotcode.vscode-mocha-latte` failed:  tty.getWindowSize is not a function
[Extension Host] Here is the error stack:  TypeError: tty.getWindowSize is not a function
    at Object.<anonymous> (/home/bob/.vscode/extensions/cspotcode.vscode-mocha-latte-0.1.2/node_modules/mocha/lib/reporters/base.js:120:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.M.d._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:28523)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bob/.vscode/extensions/cspotcode.vscode-mocha-latte-0.1.2/node_modules/mocha/lib/reporters/index.js:3:31)
Activating extension `cspotcode.vscode-mocha-latte` failed: tty.getWindowSize is not a function.
command 'mocha.runAllTests' not found
```

**Comment by acchaulk** [comment]
@bobderrico80 @beturs Have you found a workaround to be able to run the extension on Ubuntu?

**Comment by betososa** [comment]
I just updated my extension and its working ! So i will close this issue. Thanks @cspotcode very nice extension
